name: flutter_monaco_editor_example
description: Example app for flutter_monaco_editor.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_monaco_editor:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
