# Uncomment any service you use and fill in the username/project.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [outr]
# patreon: outr
# open_collective: outr
# ko_fi: outr
# tidelift: pub/flutter_monaco_editor
# custom: ["https://outr.com/"]
